version: '3'

services:

  goapp:
    container_name: goapp
    image: vitestuff/goapp
    environment:
      - air_wd=/app/project
    build:
      context: docker/goproj
    volumes:
      - consistency: cached
        source: .
        target: /app/project
        type: bind

  vite:
    container_name: vite
    image: vitestuff/vite-env
    build:
      context: docker/vitevol
      args:
        PORT: 5173
    volumes:
      - consistency: consistent
        source: ./frontend
        target: /app/frontend
        type: bind

  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    depends_on:
      - goapp
      - vite
    ports:
      - 80:80
      - 5173:5173
      - 5174:5174
    volumes:
      - ./docker/nginx:/etc/nginx:ro
