version: '3'

services:

  # goapp:
  #   container_name: goapp
  #   image: vitestuff/goapp
  #   ports:
  #     - 80:80
  #   build:
  #     context: docker/goproj
  #   volumes:
  #     - consistency: cached
  #       source: .
  #       target: /app/project
  #       type: bind

  goapp:
    container_name: goapp
    image: vitestuff/goapp
    ports:
      - 80:80
    environment:
      - air_wd=/app/project
    build:
      context: docker/goproj
    volumes:
      - consistency: cached
        source: .
        target: /app/project
        type: bind

  vite:
    container_name: vite
    image: vitestuff/vite-env
    ports:
     - 5173:5173
    build:
      context: docker/vitevol
      args:
        PORT: 5173
    volumes:
      - consistency: consistent
        source: ./frontend
        target: /app/frontend
        type: bind

