version: '3'

services:

  reverse-proxy:
    image: traefik:v2.4.7
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
    ports:
      - 80:80
      - 5173:5173
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      # - ./docker/traefik/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro
      - ./docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./docker/certs:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  goapp:
    container_name: goapp
    image: vitestuff/goapp
    environment:
      - air_wd=/app/project
    build:
      context: docker/goproj
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goapp.rule=Host(`app.localhost`)"
      - "traefik.http.services.goapp.loadbalancer.server.port=80"

    volumes:
      - consistency: cached
        source: .
        target: /app/project
        type: bind

  vite:
    container_name: vite
    image: vitestuff/vite-env
    build:
      context: docker/vitevol
      args:
        PORT: 5173
    labels:
      # https://stackoverflow.com/a/57679662/8600734
      - "traefik.enable=true"
      - "traefik.http.routers.vite.rule=Host(`vite.app.localhost`)"
      - "traefik.http.middlewares.autodetect.contenttype.autodetect=false"
      - "traefik.http.services.vite.loadbalancer.server.port=5173"
    volumes:
      - consistency: consistent
        source: ./frontend
        target: /app/frontend
        type: bind

  # reverse:
  #   container_name: reverse
  #   hostname: reverse
  #   image: nginx
  #   depends_on:
  #     - goapp
  #     - vite
  #   ports:
  #     - 443:443
  #     - 5173:5173
  #   volumes:
  #     - ./docker/nginx:/etc/nginx:ro
  #     - ./docker/certs:/etc/ssl/private:ro